spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/orders
    username: root
    password: root
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  data:
    redis:
      host: localhost
      port: 6379