spring:
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:mysql://localhost:3306/orders}
    username: ${SPRING_R2DBC_USERNAME:root}
    password: ${SPRING_R2DBC_PASSWORD:root}
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
  sql:
    init:
      mode: ${SPRING_SQL_INIT_MODE:never}
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
