spring:
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false
    discovery:
      enabled: false
    service-registry:
      auto-registration:
        enabled: false
  main:
    allow-bean-definition-overriding: true
  r2dbc:
    url: r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
  sql:
    init:
      mode: always
      schema-locations: classpath:schema-h2.sql

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health
    # IMPORTANTE: Agregar esto para tests unitarios
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
    prometheus:
      enabled: true

order:
  service:
    strategy:
      default-strategy: atLeastOnce

redis:
  retry:
    max-attempts: ${REDIS_RETRY_MAX_ATTEMPTS:3}
    backoff:
      seconds: ${REDIS_RETRY_BACKOFF_SECONDS:1}
  stream:
    min-size: ${REDIS_STREAM_MIN_SIZE:100}
    max-size: ${REDIS_STREAM_MAX_SIZE:1000}
    default-size: ${REDIS_STREAM_DEFAULT_SIZE:500}
    trim:
      interval: ${REDIS_STREAM_TRIM_INTERVAL:10000}

outbox:
  retry:
    max-attempts: ${OUTBOX_RETRY_MAX_ATTEMPTS:3}
    backoff:
      seconds: ${OUTBOX_RETRY_BACKOFF_SECONDS:1}

dlq:
  retry:
    max-attempts: ${DLQ_RETRY_MAX_ATTEMPTS:3}
    backoff:
      seconds: ${DLQ_RETRY_BACKOFF_SECONDS:1}
  process:
    interval: ${DLQ_PROCESS_INTERVAL:10000}

event:
  persistence:
    topics:
      orders:
        persistToDisk: ${EVENT_PERSISTENCE_ORDERS_PERSIST_TO_DISK:true}
        importance: ${EVENT_PERSISTENCE_ORDERS_IMPORTANCE:HIGH}
      other-topic:
        persistToDisk: ${EVENT_PERSISTENCE_OTHER_TOPIC_PERSIST_TO_DISK:false}
        importance: ${EVENT_PERSISTENCE_OTHER_TOPIC_IMPORTANCE:LOW}

logging:
  level:
    com.example.order: DEBUG
    # Simplificar logging para tests unitarios
    org.springframework.boot: WARN
    org.springframework.test: INFO
    org.testcontainers: INFO
    com.redis.testcontainers: INFO
    org.springframework.boot.autoconfigure: WARN
    io.github.resilience4j: WARN

app:
  id:
    check-collisions: ${APP_ID_CHECK_COLLISIONS:true}  # Activado por defecto en pruebas unitarias
  node-id: ${APP_NODE_ID:0}

# CAMBIO CRÍTICO: Para tests unitarios debería estar deshabilitado
resilience4j:
  fallback:
    enabled: false  # <-- Cambiar de true a false para evitar problemas