services:
  order-service:
    build:
      context: ../..  # Apunta al directorio order-service
      dockerfile: src/main/docker/Dockerfile
    image: order-service:1.0.0-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      - SPRING_R2DBC_URL=r2dbc:mysql://mysql:3306/orders
      - SPRING_R2DBC_USERNAME=root
      - SPRING_R2DBC_PASSWORD=root
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_LOGGING_LEVEL_ORG_SPRINGFRAMEWORK=DEBUG
    depends_on:
      - redis
      - mysql
    networks:
      - default

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - default

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=orders
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - default

volumes:
  mysql-data:

networks:
  default:
    driver: bridge